#!/bin/sh

alias l="exa -lah --git --group"
#alias rm="rm -I --preserve-root"
alias cp="cp -i"
alias ln="ln -i"
alias mv="mv -i"
alias mkdir="mkdir -pv"
alias mount="mount | column -t"
alias df="df -H"
alias du="du -ch"
alias rmf="rm -Rf"
