#!/bin/sh

alias l="exa -lah --git --group"
#alias rm="rm -I --preserve-root"
alias cp="cp -i"
alias ln="ln -i"
alias mv="mv -i"
alias chown="chown --preserve-root"
alias chmod="chmod --preserve-root"
alias chgrp="chgrp --preserve-root"
alias mkdir="mkdir -pv"
alias mount="mount | column -t"
alias df="df -H"
alias du="du -ch"
alias rmf="rm -Rf"

# power managment
alias reboot="sudo /sbin/reboot"
alias poweroff="sudo /sbin/poweroff"
alias halt="sudo /sbin/halt"
alias shutdown="sudo /sbin/shutdown"
